exports.queryList = {
  GET_STORE_LIST_QUERY: 'SELECT STORE_ID, STORE_NAME, STORE_CODE FROM BMS.STORE ',
  SAVE_STORE_QUERY: "INSERT INTO BMS.STORE (STORE_ID, STORE_NAME, STORE_CODE, ADDRESS, CREATED_BY, CREATED_ON) VALUES(NEXTVAL('BMS.STORE_STORE_ID_SEQ'::REGCLASS), $1, $2, $3, $4, $5)",
  GET_BOOK_LIST_QUERY: 'SELECT BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER  FROM BMS.BOOK;',

  GET_BOOK_DETAILS_QUERY: `SELECT BOOK.BOOK_ID, BOOK.BOOK_TITLE, BOOK.BOOK_DESCRIPTION, BOOK.BOOK_AUTHOR, BOOK.BOOK_PUBLISHER, BOOK.BOOK_PAGES, 
                          BOOK.STORE_CODE, STORE.STORE_NAME, STORE.ADDRESS 
                          FROM BMS.BOOK 
                          INNER JOIN BMS.STORE ON BOOK.STORE_CODE = STORE.STORE_CODE 
                          WHERE BOOK.BOOK_ID = $1`,

  SAVE_BOOK_QUERY: `INSERT INTO BMS.BOOK
                    (BOOK_ID, BOOK_TITLE, BOOK_DESCRIPTION, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_PAGES, STORE_CODE, CREATED_BY, CREATED_ON)
                    VALUES(NEXTVAL('BMS.BOOK_BOOK_ID_SEQ'::REGCLASS), $1, $2, $3, $4, $5, $6, $7, $8);`,

  UPDATE_BOOK_QUERY: `UPDATE BMS.BOOK SET BOOK_TITLE=$1, BOOK_DESCRIPTION=$2, BOOK_AUTHOR=$3, BOOK_PUBLISHER=$4,BOOK_PAGES=$5, STORE_CODE=$6, CREATED_BY=$7 , CREATED_ON=$8
                      WHERE BOOK_ID=$9
    `,

  DELETE_BOOK_QUERY: ` DELETE FROM BMS.BOOK WHERE BOOK_ID=$1 `,

  AUDIT_QUERY: `INSERT INTO BMS.APP_AUDIT (AUDIT_ID, AUDIT_ACTION, AUDIT_DATA,  AUDIT_STATUS, AUDIT_ERROR, AUDIT_BY, AUDIT_ON) VALUES(NEXTVAL('BMS.APP_AUDIT_AUDIT_ID_SEQ'::REGCLASS), $1, $2, $3, $4, $5, $6);`
}